# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  
  # Configuration commune à toutes les VMs
  config.vm.box = "ubuntu/focal64" # Ubuntu 20.04 LTS
  config.vm.box_check_update = false
  
  # Utilisateur par défaut (vagrant)
  config.ssh.insert_key = false


  # --- VM 1 : Swarm Manager ---
  config.vm.define "swarm-mgr1" do |mgr|
    mgr.vm.hostname = "swarm-mgr1"
    mgr.vm.network "private_network", ip: "192.168.56.121"
    
    mgr.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
      vb.name = "swarm-mgr1"
    end
  end


  # --- VM 2 : Swarm Worker 1 ---
  config.vm.define "swarm-node1" do |node1|
    node1.vm.hostname = "swarm-node1"
    node1.vm.network "private_network", ip: "192.168.56.122"
    
    node1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "swarm-node1"
    end
  end


  # --- VM 3 : Swarm Worker 2 ---
  config.vm.define "swarm-node2" do |node2|
    node2.vm.hostname = "swarm-node2"
    node2.vm.network "private_network", ip: "192.168.56.123"
    
    node2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "swarm-node2"
    end
  end


  # --- VM 4 : Database Server ---
  config.vm.define "dbSrv1" do |db|
    db.vm.hostname = "dbSrv1"
    db.vm.network "private_network", ip: "192.168.56.112"
    
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "dbSrv1"
    end
  end


  # --- Provisioning Ansible ---
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.inventory_path = "ansible/inventory.ini"
  end


end
